export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGNUP = 'SIGNUP'
export const GET_USER = 'GET_USER'
export const GET_GROUPS = 'GET_GROUPS'
export const GET_SELECTED_GROUP = 'GET_SELECTED_GROUP'